/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutoFinalGaleriaRouteImport } from './routes/produto-final-galeria'
import { Route as JaquetaRouteImport } from './routes/jaqueta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriaFotoIdRouteImport } from './routes/galeria-foto.$id'
import { Route as FotoIdRouteImport } from './routes/foto.$id'

const ProdutoFinalGaleriaRoute = ProdutoFinalGaleriaRouteImport.update({
  id: '/produto-final-galeria',
  path: '/produto-final-galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const JaquetaRoute = JaquetaRouteImport.update({
  id: '/jaqueta',
  path: '/jaqueta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaFotoIdRoute = GaleriaFotoIdRouteImport.update({
  id: '/galeria-foto/$id',
  path: '/galeria-foto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoIdRoute = FotoIdRouteImport.update({
  id: '/foto/$id',
  path: '/foto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jaqueta': typeof JaquetaRoute
  '/produto-final-galeria': typeof ProdutoFinalGaleriaRoute
  '/foto/$id': typeof FotoIdRoute
  '/galeria-foto/$id': typeof GaleriaFotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jaqueta': typeof JaquetaRoute
  '/produto-final-galeria': typeof ProdutoFinalGaleriaRoute
  '/foto/$id': typeof FotoIdRoute
  '/galeria-foto/$id': typeof GaleriaFotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jaqueta': typeof JaquetaRoute
  '/produto-final-galeria': typeof ProdutoFinalGaleriaRoute
  '/foto/$id': typeof FotoIdRoute
  '/galeria-foto/$id': typeof GaleriaFotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jaqueta'
    | '/produto-final-galeria'
    | '/foto/$id'
    | '/galeria-foto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jaqueta'
    | '/produto-final-galeria'
    | '/foto/$id'
    | '/galeria-foto/$id'
  id:
    | '__root__'
    | '/'
    | '/jaqueta'
    | '/produto-final-galeria'
    | '/foto/$id'
    | '/galeria-foto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JaquetaRoute: typeof JaquetaRoute
  ProdutoFinalGaleriaRoute: typeof ProdutoFinalGaleriaRoute
  FotoIdRoute: typeof FotoIdRoute
  GaleriaFotoIdRoute: typeof GaleriaFotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produto-final-galeria': {
      id: '/produto-final-galeria'
      path: '/produto-final-galeria'
      fullPath: '/produto-final-galeria'
      preLoaderRoute: typeof ProdutoFinalGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaqueta': {
      id: '/jaqueta'
      path: '/jaqueta'
      fullPath: '/jaqueta'
      preLoaderRoute: typeof JaquetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria-foto/$id': {
      id: '/galeria-foto/$id'
      path: '/galeria-foto/$id'
      fullPath: '/galeria-foto/$id'
      preLoaderRoute: typeof GaleriaFotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto/$id': {
      id: '/foto/$id'
      path: '/foto/$id'
      fullPath: '/foto/$id'
      preLoaderRoute: typeof FotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JaquetaRoute: JaquetaRoute,
  ProdutoFinalGaleriaRoute: ProdutoFinalGaleriaRoute,
  FotoIdRoute: FotoIdRoute,
  GaleriaFotoIdRoute: GaleriaFotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
